import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

import { ApplicantsProvider } from '@/context/ApplicantsContext';

const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicantsProvider>
          <Header></Header>
            {children}
          <Footer></Footer>
        </ApplicantsProvider>
      </body>
    </html>
  )
}
